export const data = [
    {
      year: 1991,
      age: 0,
      text: `Gabriel Loubier`,
      orientation: `flex flex-col sm:flex-row  gap-4 sm:items-center mr-auto sm:mr-0 `,
      width: `w-12`,
    },
    {
      year: 2008,
      age: 16,
      text: `School newspaper. I learned that if you’re pursuing knowledge it’s not work, it’s fun.`,
      orientation: `flex flex-col sm:flex-row  gap-4 items-start sm:ml-auto sm:mr-5`,
      width: `sm:w-13`,
    },
    {
      year: 2011,
      age: 19,
      text: `I went to ski in Snowbird, UT instead of accruing college debt for a course I wasn’t sure about. I was hired as a hotel housekeeper, choosing the position over others because it included a ski pass for the season. It dumped 690 inches that winter, the Bird's all-time record, which still stands till this day.`,
      orientation: `flex flex-col gap-5 items-start mr-auto sm:ml-9`,
      width: `sm:w-14`,
    },
    {
      year: 2014,
      age: 23,
      text: `General Manager of CO, a popular Asian restaurant in downtown Charleston, SC. I was in charge of 18 employees and $1.6 million in annual revenue. Here I acquired a taste for taking existing momentum, and running with it!.`,
      orientation: `flex flex-col sm:flex-row  gap-5 items-start sm:ml-12`,
      width: `sm:w-14`,
    },
    {
      year: 2016,
      age: 25,
      text: `General Manager of an on a mountain restaurant in Breckenridge, CO. I managed 60 employees, in a massive cafeteria style location where we sold burgers in their thousands along with overpriced, $6, Gatorades. In this corporate position I learned about leadership and practiced growth strategies. I gave out more ski breaks than any of the other restaurant managers at the resort because I cared about them as much, if not more. This is where I learned that a corporate job was worse than the Matrix made it seem.`,
      orientation: `flex flex-col sm:flex-row gap-5 items-start lg:mr-auto`,
      width: "sm:w-14",
    },
    {
      year: 2016,
      age: 26,
      text: `I met Bitcoin when I was desperate for a meaningful career, and thought that, if I could catch up with those already involved, I could meaningfully get onboard and ride the train of the future with them. I had $10k in the bank to use to decide my future. I figured I'd have more time if I wasn't paying rent in America. I quit. Sold everything. Moved to Vietnam. I was determined to work in the blockchain industry, and didn’t see my lack of experience in any part of the field as too big of a hurdle.`,
      orientation: `flex flex-col sm:flex-row gap-5 items-start ml-auto`,
      width: "lg:w-16",
    },
    {
      year: 2017,
      age: 26,
      text: `I started writing explainer blog pieces for ICOs. I found a salaried position as a Marketing Intern with Rivetz. The project was focused on hardware attestation using the T.E.E. as ‘blockchain worthy’ intent. Whilst doing this I traveled for 2 years, through 8 countries. I filled up my passport as I wrote detailed pieces on Rivetz’s hardware security and its role in Web 3.0. This is where I learned to trust the process and enjoy the ride.`,
      orientation: `flex flex-col sn:flex-row gap-5 items-start xl:mr-13`,
      width: `sm:w-14`,
      extras: [
        `Rivetz failed to deliver a product and went under. So this is also where I learned the small and subtle -as well as the screamingly large- differences between believing in an idea and actually building it. I am not a marketer. I am not a cat. I am a problem solver.`,
      ],
      extrasWidth: `sm:w-13`,
    },
    {
      year: 2018,
      age: 27,
      text: `Unemployed and with $25k in savings as a runway I decided I would teach myself how to code. Go big or go home. I committed.`,
      orientation: `flex flex-col gap-5 items-start `,
      width: `sm:w-13`,
    },
    {
      year: 2020,
      age: 28,
      text: `Frontend Software Engineer at Trellis, an ecommerce agency. My client work includes building headless Next and Gatsby sites. My recent promotion to their Innovation Team has me building a drag and drop ‘website builder’ with inline editing. “Designers handoff code, not figma files”. It's sick, There’re screenshots below.`,
      width: `sm:w-14`,
      orientation: `flex flex-col gap-5 ml-auto`,
    },
    {
      year: 2021,
      age: 29,
      text: `I'm getting paid to iterate, learn, and master React. Life’s good, I just bought a house in VT. I am on a solid trajectory.`,
      width: `sm:w-15`,
      orientation: `flex flex-col gap-5 mr-auto sm:ml-8`,
      extras: [
        `JS was always just a gateway drug, building the internet's democracy is the end game. I've got 2 years as a Front End Developer and 5 years learning different chess pieces before I play the game.`,
        `When I watched your videos and heard you say “Betting against engineering is betting against life itself” I realized that the time for me is now. I'm in.`,
        `Hoodies are in charge now.`,
        `How can I help?`,
      ],
      extrasWidth: `sm:w-14`,
    },
  ]